### PR TITLE
Publish built versions to epoberezkin/ajv-dist

### PR DESCRIPTION
**Pull request by ghost**
As per discussion in #320 we decided to publish built version of ajv to a separate repo.

@epoberezkin So it's up to you to create both target repo and bower package :)

### CODE REVIEW

**Comment by epoberezkin** [comment]
@dcbrwn I invited you to https://github.com/epoberezkin/ajv-dist/invitations

**Comment by ghost** [comment]
Yep, it works for this repo too.

**Comment by epoberezkin** [comment]
@dcbrwn could you please push some tag in the branch so we both can see it working? And after that force-push its removal so it's not merged?

Also, shouldn't bower.json be updated to point to a new repo?

**Comment by epoberezkin** [comment]
Actually I see something got published there... Or should it be just me publishing it to bower?

**Comment by ghost** [comment]
@epoberezkin I've pushed tag v6.0.0-publish-test-1 into my fork of ajv and it got published into the mirror. As for the repo, probably bower.json should point to the source, i. e. epoberezkin/ajv.

I intentionally unregistered my ajv-dist package after I tested that all works smoothly, since all in all you're the owner of ajv :)

_Update:_

"repository" property in bower.json doesn't matter when one registers package. According to [this](https://github.com/bower/spec/blob/master/json.md#repository) it indeed should point to source code. List of requirements for bower packages from [official docs](https://bower.io/docs/creating-packages/#register), doesn't state that it's needed either.

**Comment by ghost** [comment]
@epoberezkin you think some additional testing or changes required? Let me know if so.

**Comment by epoberezkin** [comment]
Thank you. Merged. Let's see how it works :)

**Comment by epoberezkin** [comment]
@dcbrwn it seems like it doesn't remove files that should not be there...

**Comment by ghost** [comment]
I thought that whole dist folder can be useful? or we should leave only ajv.min.js?

**Comment by epoberezkin** [comment]
The current [dist](https://cdnjs.com/libraries/ajv) doesn't have regenerator/nodent, and ajv-dist does.

I think the dist folder should be removed after cloning from ajv-dist before copying the build result over, as otherwise the files removed in build remain there.

**Comment by epoberezkin** [comment]
Probably just needs `rm -rf ../ajv-dist/dist && mkdir ../ajv-dist/dist` instead of `mkdir -p ../ajv-dist/dist`

**Pull request merged**
