### PR TITLE
Remove webpack attribute

### PR DESCRIPTION
**Pull request by idangozlan**
Since it's breaking the webpack build, helpfull on version 5 only.

**What issue does this pull request resolve?**

**What changes did you make?**

**Is there anything that requires more attention while reviewing?**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@idangozlan thank you. I assume it resolves webpack issue in 5.0.1-beta, right? I'll merge into 5.0.0.

**Comment by idangozlan** [comment]
that's right. thanks.

**Comment by epoberezkin** [comment]
@idangozlan could you please make the change in 5.0.0 branch in your fork and submit a new PR to 5.0.0 branch?

**Comment by idangozlan** [comment]
sure.

**Pull request closed without merging**
