### PR TITLE
Add in ability to coerce an array

### PR DESCRIPTION
**Pull request by willfarrell**
As per discussion at #158

### CODE REVIEW

**Comment by epoberezkin** [comment]
This is a partial solution. It coerces to array but doesn't coerce from array. Coercions should be reversible, otherwise it would fail with coercions in cases it would pass without (when anyOf/etc are used).

All rules from #158 need to be implemented before it can be merged...

| schema | data | result | pass |
| :-- | :-: | :-: | :-: |
| {type:'number'} | [5] | 5 | no |
| {type:'string'} | [5] | '5' | no |
| {type:'array',items':{type:'number'}} | 5 | [5] | yes |
| {type:'array',items':{type:'string'}} | 5 | ['5'] | yes |

**Comment by epoberezkin** [comment]
Also, please avoid unnecessary white-space changes. It's spaces, not tabs, 2 space indentations everywhere.

**Comment by epoberezkin** [comment]
Also, there should be tests of standard coercions with coerceTypes:'array' option to make sure they are not broken, and tests of array coercions with coerceTypes:true to make sure it doesn't coerce to/from array.

**Comment by willfarrell** [comment]
Sorry got distracted by my own use case. Array to other types added, more tests added, and I hope I caught all the white space changes too. Thanks for reviewing the PR.

**Comment by epoberezkin** [comment]
Thank you, I will review/merge this week.

**Comment by epoberezkin** [comment]
Getting there... :) Could you please also remove unnecessary changes of `==` to `===`? In my "book", I always use `==`/`!=` unless `===`/`!==` must be used, for several reasons :)

**Comment by epoberezkin** [comment]
By the way, this object <-> array coercions seems a bit over the top - I'd limit to scalars...

**Comment by epoberezkin** [comment]
Also it seems to be only one way at the moment, so removing it is probably better.

**Comment by epoberezkin** [comment]
Thank you. Will publish today evening.

**Comment by epoberezkin** [comment]
in 4.3.0

**Comment by jfstgermain** [comment]
It's unfortunate that non scalar coercion was dropped.  It's very useful when having to convert XML payloads to JSON.  In XML, Arrays of one object are converted to a simple object since there's no way of telling the intent of the markup eg: 
`<users>
      <name>Joe</name>
   </users>`

In our swagger file, `users` is an array but this gets transformed into:
`{users:{name:Joe}}` instead of `{users:[{name:Joe}]}`

From what I see it doesn't seem to be the case, but is there a way to add custom rules or override them?  

Thanks

**Comment by epoberezkin** [comment]
Ajv supports custom keywords, any data transformation can be defined using them. If you need to run transformation before validation you can do it with allOf keyword (in the same schema custom keywords are executed after).

**Comment by willfarrell** [comment]
Array coercion was dropped? If I write another PR, can we get it back? As @jfstgermain mentioned super useful. I use it for API query params.
FYI The docs still mention support for it: `{ coerceTypes: 'array' }`.

**Comment by epoberezkin** [comment]
@willfarrell it was not dropped. I think @jfstgermain refers to the ability to define custom coercions.

**Comment by jfstgermain** [comment]
I meant Array coercion for non scalar types...

**Comment by epoberezkin** [comment]
I see. It's quite easy to define as a custom keyword.

**Comment by jfstgermain** [comment]
Looking into how to achieve this.  I'm really impressed by the extensibility of the lib!  Great job @epoberezkin  :)

**Comment by willfarrell** [comment]
Take a look at the PR itself, maybe a PR for extending it may be in order.

**Pull request merged**
