### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by ivansieder**
**What issue does this pull request resolve?**
Corrected documentation

**What changes did you make?**
Textual change inside the Documentation

**Is there anything that requires more attention while reviewing?**
No

### CODE REVIEW

**Comment by epoberezkin** [comment]
not sure if this clarification is needed - code "performance" is an approximate metric by definition.

**Comment by epoberezkin** [comment]
ah - sorry - that's not what you corrected :)

**Comment by epoberezkin** [comment]
yes - neither reads well tbh, mine is also grammatically incorrect :) Should I just drop approximately?

**Comment by ivansieder** [comment]
Sadly my mother tongue isn't English, it's just what I've learned at school an what sounds right ^^ Translating it with Deepl results in something like "If your JSON string is valid, specialized parsing is approximately as fast as JSON.parse"

**Pull request merged**
