### PR TITLE
Add `ajv-formats` plugin to readme

### PR DESCRIPTION
**Pull request by luzlab**
**What issue does this pull request resolve?**
Updates the README doc to include a plugin

**What changes did you make?**
only modified documentation

### CODE REVIEW

**Comment by epoberezkin** [comment]
@luzlab as I wrote earlier, ajv-formats is a very generic name that implies all formats for Ajv. Also, all included formats will be split into a separate package in ajv v7, for which ajv-formats seems a logical name.

I suggested earlier and I would appreciate if you rename the package to ajv-idn-formats. Could you please do it? If you do I would reserve ajv-formats for v7.

**Comment by luzlab** [comment]
What do you think about `ajv-draft2019` instead?

The format validators for hostname and idn-hostname are implemented per RFC 1123. Earlier json schemas specify RFC 1034.

Besides, I started it because to support the new formats introduced in the 2019-09. `duration` and `uuid` were added. I was surprised that ajv already supported `uuid`. Was that in an earlier draft and got dropped at some point?

**Comment by epoberezkin** [comment]
This would be wider than the scope... Ajv-formats-2019 (or Ajv-formats-draft2019) works, if the intention is to support all additional formats introduced in 2019.

**Comment by luzlab** [comment]
Sorry for delay. I've updated the repo for the `ajv-formats` plugin to reflect the new name, but I had to open a support ticket with npm about the name. I'll publish as soon as I can resolve that.

**Comment by luzlab** [comment]
Alright, NPM finally gave the me `ajv-formats-draft2019` package name.

1. published to NPM under `ajv-formats-draft2019`
2. new github repo under `ajv-formats-draft2019`
3. deleted old repo at `ajv-formats`
4. deprecated the `ajv-formats` npm package and added message about the new name.

Thank you for your patience! And thank you for all your work on AJV.

**Comment by luzlab** [comment]
@epoberezkin I just added you as a maintainer on the `ajv-formats` module. you can just leave me as a maintainer if you'd like. Otherwise we'll have to check with npm support to transfer it... 🤦🏻‍♂️😩🙁

Fortunately I stuck to the interface in the README, so it would version bump to whatever comes next.

Cheers

**Pull request merged**
