### PR TITLE
Fix punycode deprecation warning

### LINKED ISSUE #2350: Deprecation Warning: punycode Dependency via uri-js
Version 8.12.0, Node 21.2.0, using npm.

Hi there,
I wanted to raise an issue regarding `uri-js` dependency, which uses `punycode` under the hood, which has been deprecated.

While working with ajv, I've noticed deprecation warnings related to the usage of the `punycode` module through its dependency on uri-js. It seems uri-js hasn't been updated for three years, causing these warnings.

├─┬ ajv@8.12.0
│ └─┬ uri-js@4.4.1
│   └── punycode@2.3.0

Just thought I'd bring this up for consideration. Thank you for your work on ajv!

### PR DESCRIPTION
**Pull request by kibertoad**
fixes #2350 #2343

**What issue does this pull request resolve?**

punycode warnings. See linked issues.

**What changes did you make?**

Switched dependency to a fork that addresses the issue, and which is intended to be maintained for a long time.

**Is there anything that requires more attention while reviewing?**

No.

### CODE REVIEW

**Comment by kibertoad** [comment]
@epoberezkin CI appears to be broken in this repo overall. Can I help with that?

**Comment by kibertoad** [comment]
@jasoniangreen any chance you could take a look?

**Comment by jasoniangreen** [comment]
Hi @kibertoad sorry for the late reply. I have been speaking to @epoberezkin and he wants me to explore removing uri-js. It's not needed anymore for node given we are dropping older versions, but there is just an open question around browser support. I will update you when I have more.

**Comment by kibertoad** [comment]
great news! thank you

**Comment by tianyingchun** [comment]
https://github.com/ajv-validator/ajv/pull/2415, also have this PR

**Comment by jasoniangreen** [comment]
I think if anything we'll go with https://github.com/ajv-validator/ajv/pull/2415 or moving to a native approach so will close this.

**Comment by kibertoad** [comment]
@jasoniangreen makes sense. what's preventing #2415 from being merged at this point?

**Pull request closed without merging**
