### PR TITLE
Test for integer coercion

### PR DESCRIPTION
**Pull request by igor-savin-ht**
**What issue does this pull request resolve?**

Reproduces problem described in #693 

**What changes did you make?**

Add failing skipped test.

**Is there anything that requires more attention while reviewing?**

No.

### CODE REVIEW

**Comment by epoberezkin** [comment]
I am confused. All these cases work for me (https://runkit.com/esp/5a7761e3d1a7fd0012e44ede). What exactly is not working as you expect?

**Comment by epoberezkin** [comment]
... and the skipped test passes.

**Comment by igor-savin-ht** [comment]
@epoberezkin Do you see any value in new test? I can un-skip and rebase this PR, or just close it.

**Comment by igor-savin-ht** [comment]
And it probably was failing at first due to incorrect check that was removed in https://github.com/epoberezkin/ajv/pull/694/commits/a8a4ddc2fc8bb252839f9f1ea1a659f8edef5e1d and in a hurry I didn't check if test was still failing after I removed it. Sorry.

**Comment by epoberezkin** [comment]
Yes, if integer wasn’t separately tested before it makes sense to have them - let’s uskip & merge.
Thank you

**Comment by igor-savin-ht** [comment]
@epoberezkin Done.

**Pull request merged**
