### PR TITLE
Copy jsdoc comments to typescript definition file

### PR DESCRIPTION
**Pull request by HolgerJeromin**
VisualStudio uses the jsdoc of this file for tooltip.

### CODE REVIEW

**Comment by epoberezkin** [comment]
@HolgerJeromin thank you. Looks mostly good, although there are cases when jsdoc is not consistent with typescript (@this Ajv, private parameters).

@blakeembrey can you please have a look? Thank you.

**Comment by HolgerJeromin** [comment]
Good catch. I can adjust TS if it is desirable.
Adding definition of the schema itself (for example [this](https://gist.github.com/enriched/c84a2a99f886654149908091a3183e15) from @enriched) would be a benefit, too.

**Comment by epoberezkin** [comment]
You meant "adjust jsdoc" I think? These are not public parameters.
Not sure about the need to include meta-schema in typescript format...

**Comment by HolgerJeromin** [comment]
I meant ts. But adjusting jsdoc seems to be better, yes. 
People handling json schemas wants to have a meta schema for ts. Tv4 have one included. 
But including is not really needed.

**Comment by blakeembrey** [comment]
FWIW, I have a JSON schema definition in Typings already: https://github.com/typed-typings/lib-json-schema/blob/master/v4/index.d.ts.

The PR looks good, subjective to @epoberezkin for formatting/whitespace/etc.

**Comment by epoberezkin** [comment]
@blakeembrey thank you. The problem with existing JSON-schema definitions is that Ajv also supports v5 proposals. So I would leave it as Object for now.

@HolgerJeromin will you update those jsdocs then?

**Comment by HolgerJeromin** [comment]
`skipValidation` in `addMetaSchema` is not in the README but not marked as internal Parameter in jsdoc. Perhaps this needs adjustment. I removed it. Same with throwOrLogError in validateSchema.

I added `errors?: Array<ErrorObject>;` on the instance, which was missing.

**Comment by epoberezkin** [comment]
Thank you!

**Pull request merged**
