### PR TITLE
Fixed esModuleInterop compatibility error

### PR DESCRIPTION
**Pull request by root-talis**
**What issue does this pull request resolve?**
Issue #1655.

**What changes did you make?**
Fixed imports in `lib/compile/resolve.ts`.

**Is there anything that requires more attention while reviewing?**
I'm not sure how this can be covered in tests, so no tests supplied. Also, I'm not sure that this fix will not break any other usecases.

### CODE REVIEW

**Comment by heartforit** [comment]
I fell on this as well. This is very annoying. It is not in the master branch, as you can see here for yourself:
https://github.com/ajv-validator/ajv/blob/master/lib/compile/resolve.ts
Maybe somone reversed it.

**Comment by heartforit** [comment]
I opened pull-request:
https://github.com/heartforit/ajv/tree/heartforit-patch-1

**Comment by heartforit** [comment]
Adding  `"ajv": "git+https://github.com/heartforit/ajv.git"` as dependency in package.json could fix it for now.

**Comment by smelamud** [comment]
I've also stuck on this error. I don't know, why this PR was closed, this fix is really needed. I've just reproduced this bug in my Node.js project, while the same ajv version in a React project compiles OK. Possibly, because the React project uses webpack.

**Pull request closed without merging**
