### PR TITLE
Support JSON pointers

### PR DESCRIPTION
**Pull request by blakeembrey**
Attempting #32. Please review this carefully, I'm not 100% if this is the right approach (took me long enough to the hang of the templating and what was happening).

Edit: Got to do some more tidy up to add the `.replace('" + "', '')` behaviour back.

### CODE REVIEW

**Comment by blakeembrey** [comment]
@epoberezkin Ok, tidied up the output. Strings are maximally joined together at compilation time by using single quotes consistently (I think previously `missingProperty` would not have joined because it used the escape method which uses single quotes).

Edit: I used the key `useJsonPointers` as it seemed more natural.

**Comment by epoberezkin** [comment]
The option can be even shorter by the way: `{ jsonPointers: true }`.

It looks like I added all the comments in your branch, rather than in PR... It got them here anyway, but without code context. 

Do you want to me to fix all those issues or you'd rather look at them yourself? I don't mind either way.

**Comment by epoberezkin** [comment]
Actually maybe it does differentiate - just noticed that you call two different functions - `getPath` and `getPathExpr` :) Let me have a look again

**Comment by epoberezkin** [comment]
It's impressive that you've figured how it works by the way... I get lost almost every time :)

**Comment by epoberezkin** [comment]
Ok, so apart from ~~two places~~ one place it uses `getPathExpr` for validation time variable names and `getPath` for compile time key/index. Am I right? Is it an error in ~~those two places~~ this one place :) or am I missing something?

**Comment by epoberezkin** [comment]
@blakeembrey please comment on my comments - I've finished reviewing. Great stuff.

**Comment by blakeembrey** [comment]
> Ok, so apart from one place it uses getPathExpr for validation time variable names and getPath for compile time key/index. Am I right?

Yes, pretty much. I just based the code on the type of code it was replacing though, so depending on which syntax you used I replaced it with the the runtime or compile time path expression.

> The option can be even shorter by the way

Using that now.

> it will escape quotes twice. is it intentional here?

I don't think that was intentional. I should get some tests for that later.

> We should keep both the current test (without json pointers) and the new one

I guess you could add another test with it enabled. I just changed only `fullAjv` tests since those errors would have been tested already using the regular `ajv` object.

> I would rename it to toQuotedString; toString

Fixed.

> Also the behaviour when normal properties were appended as .key instead of ['key'] is lost.

All the same behaviour is there for keys. Some more complex nested tests probably wouldn't hurt though.

I'm guessing all the comments related to compile time and validation time keys is ok now? If I missed something or the logic is wrong, feel free to fix it up. I mostly based it on what was already there.

**Comment by epoberezkin** [comment]
Yes, it's great. Can I merge or you are going to make another commit?

**Comment by epoberezkin** [comment]
I see that I can :)

**Comment by epoberezkin** [comment]
@blakeembrey should we maybe add "#" in front of JSON pointers?

**Comment by blakeembrey** [comment]
@epoberezkin Why's that? That would be an implementation detail that doesn't have anything to do with JSON pointers.

**Comment by epoberezkin** [comment]
They usually start with #, no?

**Comment by blakeembrey** [comment]
@epoberezkin Nope, never. You might be thinking of when it's used as a URL in a reference within JSON schemas? That's only because it's the URL fragment.

**Comment by epoberezkin** [comment]
Ah, I see. Thanks for explaining...

**Pull request merged**
