### PR TITLE
Add _opts property type in Ajv.Ajv

### LINKED ISSUE #1253: using "_opt.defaultMeta" in TypeScript
**What version of Ajv are you using? Does the issue happen if you use the latest version?**
v6.12.3

**Your typescript code**

```typescript
import metaSchema from 'ajv/lib/refs/json-schema-draft-04.json';

// create Ajv instance(ajv) and more code...
ajv._opts.defaultMeta = metaSchema.id;
...
```

**Typescript compiler error messages**

```
Property '_opts' does not exist on type 'Ajv'.
```

**Describe the change that should be made to address the issue?**
Add type definition for "_opt".
Please tell me If there are other solutions.

**Are you going to resolve the issue?**
I'll do this if a fix is ​​needed.

### PR DESCRIPTION
**Pull request by b4h0-c4t**
**What issue does this pull request resolve?**
resolve #1253 issue.

**What changes did you make?**
Add type declaration Ajv.Ajv._opt

**Is there anything that requires more attention while reviewing?**
The reason why I set any type is other any object( ex. `_metaOpts` ) could not compatible with detailed objects.

### CODE REVIEW

**Review by epoberezkin — CHANGES_REQUESTED** [review]
Shouldn’t it be the same interface as for Options?

**Comment by b4h0-c4t** [comment]
@epoberezkin 
Thanks for your review.
I think `Options` do not have some `x._opts` properties. (e.x. defaultMeta)

**Comment by b4h0-c4t** [comment]
Self-resolved.
`defaultMeta` can translated `meta`.

**Comment by epoberezkin** [comment]
I am thinking it may be best to wait a bit until v7 is released in a week or so...

**Comment by epoberezkin** [comment]
It might be important to access this property though - defaultMeta is not the same as meta, so it should be added too.

Merging it.

**Comment by alasdairhurst** [comment]
@epoberezkin @b4h0-c4t is `defaultMeta` intended to be accessed exclusively via ajv._opts or is it available to be set in the constructor as part of the public API?

right now it's undocumented and i don't see  any recommendation for using it other than from the old v5 docs, but it seems to work if you set it in the constructor as long as you add the relevant metaSchema straight afterwards. Maybe i'm missing something important though.

**Pull request merged**
