### PR TITLE
chore(package): update uglify-js to version 3.4.6

### PR DESCRIPTION
**Pull request by crackloi**
**What issue does this pull request resolve?**

**What changes did you make?**

**Is there anything that requires more attention while reviewing?**

### CODE REVIEW

**Comment by crackloi** [comment]
K

**Review by crackloi — COMMENTED** [review]
K

**Comment by epoberezkin** [comment]
@crackloi why is it needed? It installs the latest 3.x.x version as is.

**Comment by epoberezkin** [comment]
closing, it is not necessary

**Pull request closed without merging**
