### PR TITLE
Use `npm scripts` for a dev cleaner workflow

### PR DESCRIPTION
**Pull request by blakeembrey**
Related to #34. I didn't touch linting as that's up to you to decide what you want to use (there's barely anything in `.jshintrc` right now anyway). 

Tests run on `pre-commit` and Travis CI will include browser tests with Karma.

### CODE REVIEW

**Comment by epoberezkin** [comment]
Great stuff. But it says conflicts... Probably because I merged another PR. Why do we need phantom by the way? I have it installed, but it perfectly runs with chrome - I suspect many people may not have it installed. I suggest removing it.

**Comment by blakeembrey** [comment]
@epoberezkin Karma can't run on Travis with Chrome, you'll need either Firefox or PhantomJS.

Edit: Also, PhantomJS installs with the `devDependencies` so all you need is still `npm install`.

**Comment by epoberezkin** [comment]
Ah... Got it.

**Comment by blakeembrey** [comment]
I'll resolve the conflicts now too :+1:

**Comment by blakeembrey** [comment]
@epoberezkin Tests passed

**Pull request merged**
