### PR TITLE
chore: update typescript to 5.4.3

### PR DESCRIPTION
**Pull request by jasoniangreen**
**What issue does this pull request resolve?**
- Update to latest TypeScript 5.4.3

**What changes did you make?**
- Updated TS and two small changes to get it working.

**Is there anything that requires more attention while reviewing?**
The change the the `Nullable` type.

### CODE REVIEW

**Comment by jasoniangreen** [comment]
Hi @erikbrinkman, EP suggested that you might be able to offer some guidance on this TypeScript error. No pressure though of course. This is only after upgrading to `TypeScript@5.4.3`.

```
Type '{ readonly type: "string"; }' is not assignable to type '{ type: "string"; } & StringKeywords & { allOf?: readonly UncheckedPartialSchema<any>[] | undefined; anyOf?: readonly UncheckedPartialSchema<any>[] | undefined; ... 4 more ...; not?: UncheckedPartialSchema<...> | undefined; } & { ...; } & { ...; }'.
        Property 'nullable' is missing in type '{ readonly type: "string"; }' but required in type '{ nullable: true; const?: null | undefined; enum?: readonly any[] | undefined; default?: any; }'.
```

The error seems to be referring to [this line](https://github.com/ajv-validator/ajv/blob/master/spec/types/json-schema.spec.ts#L60), but I can't fix it with any combination of adding the `nullable` property to that second item in the array. I tried adding the nullable prop to the string schema.

`{type: "string", nullable: false}` and `{type: "string", nullable: true}`

Whichever you put, however, you get either

`Type 'false' is not assignable to type 'true'.` or `Type 'true' is not assignable to type 'false'.`

Update 03/04/24: I managed to get everything working with [one tiny change](https://github.com/ajv-validator/ajv/pull/2404/files#diff-597070a6675a9e4879bf264816ed6932d1d5ec5198d9946250349dca5fa59602R177). However I don't have enough context to understand if this change is right or not. By changing the type to allow `nullable` to be optional, I am presuming that the code written in `spec/types/json-schema.spec.ts` is correct and the `nullable` shouldn't need to be passed, which sounds correct to me.

**Comment by jasoniangreen** [comment]
@epoberezkin fyi

**Comment by erikbrinkman** [comment]
Sorry for the delay here. Your fix is not correct, but I applaud tracking down something that works from these outrageous messages.

What you changed means if a type is undefined, you no longer need to mark it as nullable, but that's not correct, if a type is undefined, than the schema should indeed have `nullable: true`, it's not optional.

As far as the root cause, I'm still tracking it down. I find the [typescript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAxsAcgVwDZYMIAsJkBrAZwHV4BDMSeAHjSoFtoIAPYCAOwBNSopBIm4BzADRQAKuAgA+KAF4oGPhABmIiLygcufAd2xYoAfigADIUlSYcBImSjMMQqACNoCDNBFRgpMgA9tyaov5BKqTQACQA3kysAL4WUABc0rIA3ABQoJBQAKrciCFSQQCS3Fzw0ail3PSFCsoAFIW6nDz8UFTcIGZQrQD6GYUAlEoKAG5BiDoZ3BDTEPCTet0CIxki6qtQFZOKM3M65hXpUEsr8LkcYEHwwP6ysEGsAFIwAPJoMMiEZhUJRFbgAxzaL6-f6AqgySD0ADS3CCAHduJJvPJcvloMVwSRtAAFKhPRBULAwiBA+hSFpQElkilNMGEQm8KF-cFA+EQWmY+A+ORyO7sB5PF4FRnAcmU7lUWn0uA2dDGBwkCjUWiregAImlsqpQN1knxbOIxNJMopRoVdJFeVenN5tM6+h61hEEgOpANFLdmw8QSCWAgfXpFV9VtlAYM-kF0HMUigAB8VGpNEsFtJciIauoqMhoJhmJ54IiICBUY8enEclAG84RIgXMxTIsMKXVrlG84qOwW5321dO2We42OMgsK5ECsALLN1vDoxd271ifsKcz+f9wdtjur8cNlxYGVgUPfdTL0fd9cN9SPIHAYeesS5JI5POrAtF2DCMQVlWNYCHWvbMCIAAyPCiMA+DXoed59uwUFiLB8FjohYBUMANTcC+-6iEeUAPvAT74Ugb45B+uKggSFocj8XKwi6UiSJGfomBscbuMGobhiCrQAPSCf4hDRP41bpg0AgUlgaK9PA7iIAgpIDKo0lQEE6iShApCIaBvaNn0ICXhk8BhrwIRYAMZoQgx0LyixbFRkyWByAA2gAukRSSplABmGZpSymVA5lUJZ3DWbR5qQoxtpOT6HEed5iG+WmrQBYZuJmRZVkDK0yZcT0K5loMzqyHqJWrLqfm6l+ojVc5SWXIVXRxq+4TmOVCK6h1JqJdGFIKBkrXugIPEhmG3BlYxLq6hNfHcP17GDW5lzXKs4xeT5UAAGSgg05RVDUdQyiErpFYYN7wIMJZloB1bwD0I2xh6BGDMqXoPcBLWveNvFTYMcS+YsyyrHIkzpQVf0jquQOIb22VQN1fK6lV8A1WmdXVBADUY01q0Or2vn7XdqzfU9AgvZdgjveYmWI7IGQo3qfUE65RONiTf4UaIFPPdIMMLYD9MI42SMs-NAN9MtLnWm5O3U21PRhRFUXucZkgAHQ68ZXmefDgUNhLs0VbqpLUCAstJURvbKdSpAZAzRuq3lUDuYiUB+BaIBadInkALTDrZ7KcvFFVSB7nmSAWWDRAopPGFQ7ihrSUec4F3PO4FoaofgI3ubqucwfguopUbUBJLbjbgdwFRcMwjvSIXxewWXO37RlYvHv29cOwXRfQW35dc352e9LwvDKQ0FJ943GSx9EPmTErY2hblkUDHrBuixXJu-HNFtUFb7Pyxnhn2-P0V2WHjkR+5AAM0fERS8fVw2wTVFQIikMHrJ2RxW0acn7nzAiIOev8DwYQrkCdgED0K3hgSIXAIRgDf24JA2G0CjawJQV-H+CC1wV3UgARx8PAjIWJ34Tynmdbgs8G6YI2kQ0eq9AwACUiA1noB1SQxkFC7yNvvNAc0gjuAAFZEGANbQm1Dwq0JnlgIk8Agh0BlLpYcws+h+RDvRW+zF74dWfovbE3d0zLApBgbCxIVFqMQBojIWjpppl0bFByBiESRyMTHV+piK5gFsasdRmCVquRhliQYHEWR0RsaooJ9jSBAPtJcVxvBlFxLJLpJJoDGxYRwqsbg6S7EOKgJw4IT0eEEVNP-UOcU76ePct4l+cd5A5IbAEjJoBEglO+OBYA0SYr2SYtSOEFVeHNPjpIXUuJdQJ38mYxmkBhy9QIrqahVczG8AgJANQYIEnDnHr2D2Xtpo+z9lITyw5OHhTyvQVoZztJSC2p5BQLian0UAfKRU6zqFbJ2Vs6onCyGIHMrwA5CzGzHO9pWc5lyMjXLViAO5DzpDPLaZXX52zug8GALaTBhzIWe2hb7R5cLr7sk+bCb5ZiNlIMKYEzJTDrrUNgUU+JJT0YdyGKE+W4SEyGxdhAYFoL4Ub2ssimFjy0WK3dqkoFGAQXaDnNSMspBFQGxpu5ZhO95kV3MsK7QVyxVIrlUKhVoLlWrjVXSLy58Qa6sFQa3goqbmbwGXZeVireCWtVYqW1y9fo0yMDgAVgVhFzWDVgGRHNqGRuTqGShCYZXMMmPtceslLxGtdeK1JlKRl+peXI-omaXWIvdRS1a2T-VmJCBAEtpTjXlo+ZWr5NrC1mMQFeMY7zLSuWydQ2CPA-4xLSS2qldJqEQBacOwZeaaQTrMSiZ83aR1zrtHa8YqaHWBXcj7R6zraa808hkYy1CYjzHIl6M95ku2HqvWYmIWz1CYLKdw8ZqT9EjJdMiNEGJ4xCnRU+5sdCX1cIqe+ntQzw4Ih-eiAUAGfKinFM8Gin6eQRyVMIWwapzSahoHQPUaHRmQH6h+upHi+SsQma0nErxYPTWUJlXdlYMhGIyPR98fkPYojg1AHWWt6P6z8oJg2aZ0Z+Q6n5JxflI20YKLmhlwTskgiY0S05kr-ZBwyO0SDRGWJRx8S0uZdgsDxso+nSG27DIxBvaxgiiGqJIceCh14bLGXKeUJ9bD9hcOUHwzqfUimEm2lI5BtzSnW3Cjk3iSDnqLUqtWNa+kqmTlQBRRcrT6YgNZhhpHREOrmGXERO+ZjJL-ZOYlDROLSqEu1EVCCLzqofOODw9qBgupqvetq6QULI7Os+sS4qB0NETNmfq8oVQ2XtC5dDSOHAZnE0+CIp-IQ14cBER4EOUttzoZieMNKxCT6qDYGXYLPb62qKXEynGlOEBhwmOWyEVbI0NsrizWWyO7bexHZO8OKQ75cifhxvAH80A5wgAACLYWBJlB8QQ7O80Qu4UkhCoDCSgFLIINVSD4CCNgHQngoABN0jir22l5qkhqogAQxPojVCR1QAAXk7MxZCMDsAyLqNn7BdRmPchzu9Yhj2C9EKlJHwZhxYkQsADA547s5WzQMLV11JBGMQhbJ2XsD3iaSF5RCQIwCa6hdNIxqOPy9iXQAIQlwjr0aORI47x1gHQS6PDQFp6TztGOJpU5p+ZOnwBEJLFENhWcEAKjqGt0EVH6PHf47d1cXGoeVhk+98GX3RP-c4qojkHIK3ngW1tMzcjX6Krg6h2gwuFsy7Jel0zDHR8T6IUvk3ceSNdRiMkagE0ZiOnFNbxChs8wWcVz3vX7GXA8Y99H1zcQNK58V3kdPEIFJwsJIXr4hfjrzXaAyIXeYZct8NiSEfqSZDw+MMWxAOfvkqACHz7n9HsFqdewEIO9e-oOm3eYHnp7zxRhvCfAl5AgqaITo78a9B8BQCEDmR8Y6x16QCc6N7T6Ngt575xA6Sc7ow1Qn7+SYEY59SVzRz67gKX5QAABMp+S+dCDC-c1Gp+N2EAV+N+ue+ezgIAReyMwBxGfI5e0OcymU2Wy+GCI+RsyOzOXB7ipeCIfBleFOjONeZiMucuxeUh6GMhkO0OhcyhoYihxMl2jGCBTBGOneUiKBDYQhIGohgU4h1ho+se8oOkr+UAI60Bqw0A-Gg++BHeEiZhp+-iQWukdhM+DY3Omu7ebMLhf+nO3OOB-hRsJ+XheSuEa+QRVmIRvQ7gyA4R4+hBiRGR+RIR1BiiqRTcJi8RgU+qO+B6XkFRlcdROhxhBKDY4BOskBOgMBHh8BGR7eyBdRdsZB7kGB7e2B9ReBERqyRB-RNcpBdBlBXhxRK+WAECG+LS0xDYjBzB8+qUp+fy2KeyaR48yO8Ae+mOh+ZiE0wRRsS6muVRXqpxVu6eBsuB6OqiNBJgfe7K9+2ihOBIhAOgfguodxoKVO00a6XhwJu+7saMSeMoKwEeUe5xGRnxjKVxM+6OWEYSKJwSLhPx0Arg02fgmJvKgQsIekGRFusJYeCJwYORiBGO2BkgN2Ca-61+nQW4pAYec4u4rYGQD89RXhhRmcp+QpmenS6+6RjYcOdJxhKyvMcRFxpIMpWB10-UzJxhESopvYtheBNmGgnOAAxIJJYdJIJOIXEfbnAVrB4BgM8MpFAJZLpFcEEM8HRE4Z0drN0WIbSZKWGuPk4uYaPuqVsRkZtswHvliEycYMQRXFqeLLLiyRgXqeoIacaRoMBqaY0Raa0daSiDdJ0VrGYhrgpPALaJIDmdIIQL0KeAUsnr4G-pEFNl7M8BsPAPQjgAMAHG4bAfaXRG-rIGYgbmiVlOPqYd3usevE6nvjGUUZPMIavoEa3t4aMXGcfnUY8fDuMbkaslGfNrdlfgKRXMHnWTSZucMePoyXNqZvuayYebPurnOe8aUasdEKfpCTUbqHDv1PId+dXlMgbofpacZJpIOjdNiVvJPNNp0VANWNwAAOQuaQB0SXZ35REYLABAA) is helpful for figuring these things out.

The problem isn't in directly checking the definitions, it's actually in the way we define `SomeJSONSchema`, particularly for tuple types, and particularly for every member beyond the first of a tuple type. This manifests in the following way:

```ts
const _: SomeJSONSchema = {
    // ... and here ...
    type: "array",
    items: [{ type: "number" }, { type: "string", nullable: true }],
    minItems: 2,
    additionalItems: false,
}
```

type checks fine, but if you remove the nullable for the string item, it fails. As far as I can tell, this traces back to how we define:
```ts
type SomeJSONSchema = UncheckedJSONSchemaType<Known, true>
type Known = {
    key: string]: Known;
} | [Known, ...Known[]] | Known[] | number | string | boolean | null
```
particularly the tuple definition `[Known, ...Known[]]`

I need to understand better how typescript interprets this tuple expansion, but I think it went from being essentially a heterogeneous tuple, to being a tuple with one element, and then a homogenous array, which screws up the inference.

I think realistically the defintion of `SomeJSONSchema` is hacky, and should probably just be defined more manually, which will prevent these errors, but will make updates a little more difficult.

**Comment by jasoniangreen** [comment]
Hmm, interesting. In the meantime @erikbrinkman what about this bump instead?
https://github.com/ajv-validator/ajv/pull/2406

Not sure if you're able to review PRs, but feel free to give it a tick if you think this is ok.

**Comment by jasoniangreen** [comment]
Closing for now as we have an update to 5.3.3 without any changes needed.

**Pull request closed without merging**
