### PR TITLE
Bugfix should skip extendError if "error" option is "full" for custom keyword validate function

### PR DESCRIPTION
**Pull request by PhoenixHe-NV**
**What issue does this pull request resolve?**
#1244

**What changes did you make?**

**Is there anything that requires more attention while reviewing?**

### CODE REVIEW

**Comment by PhoenixHe-NV** [comment]
Will add test later

**Comment by PhoenixHe-NV** [comment]
@epoberezkin Could you please help to review this PR？Our product depends a lot on error reporting in ajv and is currently blocked by this bug. Thanks！

**Comment by epoberezkin** [comment]
@NullMDR Thank you. I am looking. I think there might have been some reasoning behind the decision to call extend anyway, trying to find the traces from the time...

**Comment by PhoenixHe-NV** [comment]
@epoberezkin Any update on this one?

**Comment by PhoenixHe-NV** [comment]
ping @epoberezkin

**Comment by PhoenixHe-NV** [comment]
ping @epoberezkin . Our code depends on ajv will go live soon and because of this bug we still need to maintain a fork of ajv. Could you please help to review this PR?

**Comment by epoberezkin** [comment]
Sorry for the delay - I've reviewed it now.

The reason that the errors are extended with `dataPath` and `schemaPath` properties in all cases but custom **inline** keywords and `errors: "full"` option of a custom keyword, is that "compile", "validate" or "macro" custom keywords (i.e. all but inline keywords) do not have the current schema path to include it in errors. The "full" value of this option is only intended for "inline" keywords - so the current behaviour is not a bug, it is documented here: https://github.com/ajv-validator/ajv/blob/master/CUSTOM.md#reporting-errors-in-custom-keywords.

I think that it would be a breaking change and it would also require changing API to pass `schemaPath` to custom keywords or, maybe, extending errors only with `schemaPath` leaving `dataPath` as is if it is present. We need to think how custom keywords other than inline should change in v7, there are many objectives for keywords - I am working on it now.

Also, currently dataPath is overridden by extendError [only if it is not set](https://github.com/ajv-validator/ajv/blob/master/lib/dot/custom.jst#L68) - so you already can set dataPath in your errors. If you need to have `data` property in errors, you need to use `verbose: true` option in Ajv (although in your test case it would be the whole object rather than the specific property - it is where keyword is defined). Any other information can be included in `params` property of the error.

A smaller possible change would be to only set `.data` property in errors only if it is not already set ([here](https://github.com/ajv-validator/ajv/blob/master/lib/dot/custom.jst#L75)) - that would allow setting it in your custom keyword handler. If this line is changed to `if ({{=$ruleErr}}.data === undefined) {{=$ruleErr}}.data = {{=$data}};` your test would pass. That may be an option for v6 - I will think about it.

**Comment by epoberezkin** [comment]
@NullMDR would this change work for you?

**Comment by PhoenixHe-NV** [comment]
Oh yes thanks @epoberezkin . I'll test again with your proposed changes for check data undefined in extendError. 

What do you mean by "an option for v6"? And what's v7 anyway?

**Comment by epoberezkin** [comment]
> What do you mean by "an option for v6"

this change could be possible in the current major version of Ajv (v6)

> And what's v7 anyway?

the next major version (WIP in v7-alpha branch)

**Comment by epoberezkin** [comment]
closing it, the code has completely changed now.

**Pull request closed without merging**
