### PR TITLE
feat: ES module default export interop

### PR DESCRIPTION
**Pull request by bradleyayers**
**What issue does this pull request resolve?**

#687 

**What changes did you make?**

- Added a `default` property on the package top-level module.
- Changed the TypeScript definition to use an ES module default export. This will require TypeScript consumers to change `import Ajv = require('ajv')` to `import Ajx from 'ajv'`.

**Is there anything that requires more attention while reviewing?**

### CODE REVIEW

**Comment by epoberezkin** [comment]
> Changed the TypeScript definition to use an ES module default export. This will require TypeScript consumers to change import Ajv = require('ajv') to import Ajx from 'ajv'.

It should be in the next major version then.

**Comment by bradleyayers** [comment]
> It should be in the next major version then.

I've amended the comment to include `BREAKING CHANGE`.

**Comment by thomasgwatson** [comment]
Yay, thanks for this

**Review by SelfMade1101 — APPROVED** [review]

**Comment by CrispusDH** [comment]
any updates?

**Comment by moderndeveloperllc** [comment]
This would be so useful. Not only for TS folks, but for those of us writing web components which are ES6. In my use case, I would like to do some browser-side validation before I send off an API call. I have a web component for all the API work that this would fit quite nicely in if I could import it properly.

**Comment by nicferrier** [comment]
hello! is there  another solution to this? or is it just stalled?

**Comment by giacomo-cosimato** [comment]
Is this going to be merged anytime soon?

**Comment by marcospassos** [comment]
Super useful!

**Comment by kuldeepdaftary** [comment]
Any updates on this please @epoberezkin?

**Comment by epoberezkin** [comment]
As I wrote above, it should be merged in the next major versions as it requires the update of the code that uses it:  https://github.com/epoberezkin/ajv/pull/748#issuecomment-377728201

**Comment by alexs-mparticle** [comment]
Love this change and I'm eager to use it in my project. Any idea when it'll be ready to go?

**Comment by asap** [comment]
Love this change and it'll help in my current project. Any idea when this will be ready to go?

**Comment by epoberezkin** [comment]
It’s switched to ESM/typescript modules in v7 - see Getting started.

**Pull request closed without merging**
