### PR TITLE
replace Object to object due (Object=any), add CompilationContext interface

### PR DESCRIPTION
**Pull request by delagen**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@Delagen could you please remove unnecessary whitespace and line order changes so it's easier to see what has really changed?

**Comment by delagen** [comment]
@epoberezkin OK ) Webstorm autoformat ))

**Comment by epoberezkin** [comment]
@blakeembrey could you please comment on "Object" vs "object" and "String" vs "string"?

**Comment by blakeembrey** [comment]
@epoberezkin It makes sense, added in TypeScript 2.2 (https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#object-type). It's much more useful than `Object` since pretty much everything extends from the type `Object` while `object` is a new type primitive (JavaScript primitives aren't assignable).

**Comment by epoberezkin** [comment]
@blakeembrey @Delagen thank you

**Comment by delagen** [comment]
@epoberezkin You are welcome. Your project saves a lot of time in development. The only feature I still need is method of get a result schema with all macro resolved and all references included. I implemented some sort of this in my wrapper, but native method would be awesome

**Comment by epoberezkin** [comment]
@Delagen see https://github.com/epoberezkin/ajv/blob/master/FAQ.md#generating-schemas-with-resolved-references-ref

**Comment by delagen** [comment]
@epoberezkin I read this note already. Thanks.

**Pull request merged**
