### PR TITLE
errorsText: Fallback to this.errors for null/undefined

### PR DESCRIPTION
**Pull request by orgads**
**What issue does this pull request resolve?**
Backwards compatibility with v6.

**What changes did you make?**
Fallback to this.errors when the input is null/undefined.

### CODE REVIEW

**Comment by epoberezkin** [comment]
I am probably missing something - what does it change? It would help to have a failing test that this change fixes or at least an example (to begin with, there probably has to be the test anyway if it is a regression)...

**Comment by orgads** [comment]
If the user calls `ajv.errorsText(null)`, it used to use `this.errors`, but now it just shows `No errors`.

**Comment by epoberezkin** [comment]
That's what I thought - but it means it was incorrect in v6.

The use case is that if you call it as `ajv.errorsText()` it should use `ajv.errors`, but if you call it as `ajv.errorsText(validate.errors)`, and `validate.errors` can be `null`, it should always use `validate.errors`, and if it is `null` it should return "No errors".

I may still be missing something, but it may be that there ~~was~~ is a bug in v6?

**Comment by orgads** [comment]
I see. Then how do you suggest to pass options, but still use `ajv.errors`? Pass it directly: `ajv.errorsText(ajv.errors, { ... })`?

**Comment by epoberezkin** [comment]
yes, that was the idea. Agree it's not the nicest API - we can change it in v8 which would be Q1'20 anyway.

**Comment by orgads** [comment]
Q1'21 probably :)

**Comment by orgads** [comment]
So that's what we did. I'll close it then. But you can probably expect it to pop from other users :)

**Comment by epoberezkin** [comment]
right :) Classic New year mistake. Anyway, open to suggestions on the different API... Maybe Ajv should export the function to pass `validate.errors` to and the method only accepts options and doesn't accepts options (everybody would break though:)

**Comment by epoberezkin** [comment]
how was it even working if you pass null?... Maybe it was working because users never combined `ajv.validate` approach with `ajv.compile` approach, but whoever did combine it on the same instance would have bugs in v6...

**Comment by epoberezkin** [comment]
or do docs suggest to pass null?...

**Comment by epoberezkin** [comment]
I've actually found some cases when I had to pass ajv.errors explicitly - it is an annoying API...

**Comment by orgads** [comment]
There, [on v6](https://github.com/ajv-validator/ajv/blob/v6/lib/ajv.js#L412) it was:
```
  errors = errors || this.errors;
  if (!errors) return 'No errors';
```

[The docs](https://github.com/ajv-validator/ajv/tree/v6#errorstextarrayobject-errors--object-options---string) don't say much about this argument.

**Comment by epoberezkin** [comment]
Yeah, it was bug-prone I think.

**Pull request closed without merging**
