### PR TITLE
Use root schemaEnv when resolving references in oneOf

### LINKED ISSUE #1899: Using `discriminator` in a definition causes failure to compile if `oneOf` contains a reference
**What version of Ajv are you using? Does the issue happen if you use the latest version?**

`8.10.0`

**Ajv options object**

```javascript
{ discriminator: true }
```

**JSON Schema**

```json
{
  "type": "object",
  "properties": {
    "container": {
      "$ref": "#/definitions/Container"
    }
  },
  "definitions": {
    "Block": {
      "type": "object",
      "properties": {
        "_type": {
          "type": "string",
          "enum": ["foobar"]
        }
      },
      "required": ["_type"],
      "title": "Block"
    },
    "Container": {
      "type": "object",
      "properties": {
        "object": {
          "type": "object",
          "oneOf": [
            {
              "$ref": "#/definitions/Block"
            }
          ],
          "discriminator": {
            "propertyName": "_type"
          },
          "required": ["_type"]
        },
        "array": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/Block"
              }
            ],
            "discriminator": {
              "propertyName": "_type"
            },
            "required": ["_type"]
          }
        }
      }
    }
  }
}
```

**Sample data**

n/a

**Your code**

```javascript
var ajv = new Ajv(options);
var validate = ajv.compile(schema);
```

**Validation result, data AFTER validation, error messages**

```
Error: discriminator: oneOf subschemas (or referenced schemas) must have "properties/_type"
```

**What results did you expect?**

The schema to compile.

**Are you going to resolve the issue?**

Not immediately. 

**Reproduction**

https://runkit.com/mshick/620a919455b3e30009ef1f50

### PR DESCRIPTION
**Pull request by asprouse**
**What issue does this pull request resolve?**

Fixes #1899

**What changes did you make?**

[Use root schemaEnv when resolving references in oneOf](https://github.com/ajv-validator/ajv/commit/d7f91f6569b55bc241057f37fa1910c6998eb1ec)

**Is there anything that requires more attention while reviewing?**

No this should be a simple fix

### CODE REVIEW

**Review by mcat — APPROVED** [review]
👍

**Comment by epoberezkin** [comment]
Great!

**Comment by asaneh** [comment]
#1913 #1912 #1923

**Comment by asprouse** [comment]
@epoberezkin I know you are probably very busy, but is it possible to cut a 8.10.1 release so that this fix is available via npm?

**Comment by metinogurlu** [comment]
@epoberezkin I am waiting for the next release too, do you have any prediction about that?

**Comment by epoberezkin** [comment]
right, sorry - it was nagging me that I didn't do it - thanks for the pings - will do today/tomorrow!

**Comment by epoberezkin** [comment]
It’s released now

**Pull request merged**
